name: Publish Python Package

on:
  release:
    types: [created]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
        cache-dependency-path: pyproject.toml
    - name: Install dependencies
      run: |
        pip install '.[test]'
    - name: Run tests
      run: |
        pytest
  deploy:
    runs-on: ubuntu-latest
    needs: [test]
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        cache: pip
        cache-dependency-path: pyproject.toml
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install cibuildwheel
    # ------------------------------------------
    # Build Wheels Using cibuildwheel
    # ------------------------------------------
    - name: Build Wheels
      env:
        CIBW_BUILD: "cp39-* cp310-* cp311-* cp312-*"

        # Only build 64-bit manylinux wheels, skip musllinux
        CIBW_ARCHS_LINUX: "x86_64"
        CIBW_SKIP: "*-win32 *-musllinux_*"

        # Force a valid manylinux image (avoid date-based tags)
        CIBW_MANYLINUX_X86_64_IMAGE: "quay.io/pypa/manylinux2014_x86_64:latest"

        # Force the wheel's minimum macOS version to 14.0
        MACOSX_DEPLOYMENT_TARGET: "14.0"

      run: |
        # This will build wheels for all supported Python versions on the current OS.
        # By default, it runs a "pip wheel ." inside each Python interpreter environment.
        python -m cibuildwheel --output-dir dist

    - name: Show built wheels
      run: ls -l dist
    - name: Publish package distributions to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/

